---
title: "methods-technical"
author: "Tim Disher"
date: "2023-01-30"
output: html_document
---
# Methods

## Daniels and Hughes Surrogate model

The Daniels and Hughes Bayesian Random-Effects Meta-Analysis (BRMA) model is a
statistical model that incorporates both fixed-effect and random-effect
components. By modeling the effect on the surrogate outcome as a fixed effect,
the model avoids potential pitfalls of borrowing strength across studies as can
happen in models that treat the effect on the surrogate outcome as a random
effect. The model is formulated in a Bayesian framework, which allows for the
incorporation of prior information and estimation of model parameters based on a
posterior distribution. Mathematically, the Daniels and Hughes BRMA model can be
represented as:


$\begin{aligned}
\begin{multline}
\binom{Y_{1i}}{Y{2i}} \sim \mathcal{N}\left(   \begin{pmatrix} \delta_{1i} \\ \delta{2i} \end{pmatrix}, \begin{pmatrix} \sigma^2_{1i}
 &  \sigma^2_{1i}\sigma^2_{2i}\rho^{12}_{wi} \\
\sigma^2_{1i}\sigma^2_{2i}\rho^{12}_{wi} & \sigma^2_{2i}
\end{pmatrix}\right)\\
\delta_{2i} |\delta_{1i} \sim \mathcal{N}\left( \lambda_0 + \lambda_1\delta_{1i},\psi^2_2\right)
\end{multline}
\end{aligned}$

The true effects $\delta_{1i}$ as measured by the surrogate endpoint are considered to be study-specific fixed effects in each study and have a linear association with the true final outcomes $\delta_{2i}$. All parameters are given generally vague priors.

## Extension to Multi-treatment Context

The Daniels and Hughes Bayesian Random-Effects Meta-Analysis (BRMA) model can be generalized to the multi-treatment context of network meta-analysis (NMA).  This generalization is represented mathematically as:

$\begin{aligned}
\begin{multline}
\binom{Y_{1i}}{Y{2i}} \sim \mathcal{N}\left(   \begin{pmatrix} \delta_{1i} \\ \delta{2i} \end{pmatrix}, \begin{pmatrix} \sigma^2_{1i}
 &  \sigma^2_{1i}\sigma^2_{2i}\rho^{12}_{wi} \\
\sigma^2_{1i}\sigma^2_{2i}\rho^{12}_{wi} & \sigma^2_{2i}
\end{pmatrix}\right)\\
\delta_{2i} |\delta_{1i} \sim \mathcal{N}\left( \lambda_{0t_{i1},t_{i2}} + \lambda_{1t_{i1},t_{i2}}\delta_{1t_{i1},t_{i2}},\psi^2_2\right)
\end{multline}
\end{aligned}$


Where the only change is to create a separate $\lambda_0$, $\lambda_1$, and $\delta_1$ for each treatment contrast. We allow $\psi^2$
to be shared across contrasts. This generalization of the model to the NMA context is important because the relationship between the surrogate and the final outcome can differ depending on the classes or underlying mechanisms of the treatments being compared. By fitting separate means and random-effects for each contrast, the model accounts for these differences and provides an opportunity to evaluate whether relationships differ importantly across comparisons. Note that because of how
contrasts are coded, this code shares the same important caveat as inconsistency
NMA code: namely that treatments must always be arranged in ascending order. It is tempting to add an additional hierarchy to state that each of the relationships come from some shared distribution. This would have the benefit of allowing conceptually for an unevaluated contrast to be treated as a random sample from this overarching distribution but it would seem better to use existing NMA generalizations of BRMA models instead. Those models leverage the first and second order consistency assumptions and wrestle with difficulties with identifiability that suggest the endeavor may be
more complex than it seems.


